image: docker:28

stages:
  - build

before_script:
  - echo -n $DOCKERHUB_TOKEN | docker login -u edwardgordin --password-stdin

Build:
  stage: build
  script:
    - docker build -t edwardgordin/candlestick-service .
    - docker push edwardgordin/candlestick-service
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH