services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - PGDATA
    expose:
      - ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
