"""candle_span

Revision ID: 63da74ca4f93
Revises: f664629df52b
Create Date: 2025-03-11 16:17:31.680977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63da74ca4f93'
down_revision: Union[str, None] = 'f664629df52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle_span',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_till', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candle_span')
    # ### end Alembic commands ###
