"""add index to candle

Revision ID: 8fc69277d64f
Revises: 714c171969c0
Create Date: 2025-02-18 17:34:37.985432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc69277d64f'
down_revision: Union[str, None] = '714c171969c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_candle_unique', 'candle', ['security_id', 'timeframe', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_candle_unique', table_name='candle')
    # ### end Alembic commands ###
